name: habit_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+4

environment:
  sdk: ^3.9.0

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  glossy: ^0.0.5
  haptic_feedback: ^0.5.1+1
  intl: ^0.20.2
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  lottie: ^3.3.1
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  purchases_flutter: ^9.4.0
  purchases_ui_flutter: ^9.4.0
  shared_preferences: ^2.5.3
  unicode_emojis: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13

flutter_launcher_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path: "assets/images/HabitTrackerLogo.png"
  image_path_ios_dark_transparent: "assets/images/HabitTrackerDarkLogo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
  fonts:
    - family: MonaSans
      fonts:
        - asset: assets/fonts/MonaSans-Regular.ttf
        - asset: assets/fonts/MonaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/MonaSans-Italic.ttf
          style: italic
